language: java
install: true

before_install:
  - chmod +x gradlew
  - ./gradlew assemble
  - ./gradlew check

os: linux
jdk: oraclejdk12

script:
  - ./gradlew build

#after_success:
#  - sbt coveralls