version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      #- ./dump_staging.sql:/docker-entrypoint-initdb.d/dump_staging.sql
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kanban_development
      PGDATA: /tmp
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - db

  graphite:
    image: graphiteapp/docker-graphite-statsd
    ports:
      - 8087:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - graphite